/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aurochat;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author elalf
 */
public class Login extends javax.swing.JFrame {

    public static String ip1;
    public static String ip2;
    public static String ip3;
    public static String ip4;

    public static String ip;
    
    public static String usernom;
    /**
     * Creates new form NewJFrame1
     */
    public Login() {
        initComponents();
        ip1 = "192";
        ip2 = "168";
        ip3 = "1";
        ip4 = "91";

        ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4;
        usernom="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginWindow = new javax.swing.JPanel();
        txt_passw = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        btn_send2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_ip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AuroChat");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LoginWindow.setBackground(new java.awt.Color(37, 44, 52));

        txt_passw.setBackground(new java.awt.Color(37, 44, 52));
        txt_passw.setForeground(new java.awt.Color(255, 255, 255));
        txt_passw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_passw.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        txt_usuario.setBackground(new java.awt.Color(37, 44, 52));
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_usuario.setCaretColor(new java.awt.Color(255, 255, 255));

        btn_send2.setBackground(new java.awt.Color(204, 204, 204));
        btn_send2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_send2.setForeground(new java.awt.Color(51, 51, 51));
        btn_send2.setBorder(null);
        btn_send2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_send2.setLabel("Entrar");
        btn_send2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Usuario");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Contraseña");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aurochat/mess4.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Bienvenido a");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("AuroChat");
        jLabel15.setToolTipText("");

        Registro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("No tienes una cuenta?... Registrate aqui!");
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aurochat/barra.jpg"))); // NOI18N

        lbl_ip.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl_ip.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ip.setText("Aqui puedes cambiar la ip");
        lbl_ip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ipMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginWindowLayout = new javax.swing.GroupLayout(LoginWindow);
        LoginWindow.setLayout(LoginWindowLayout);
        LoginWindowLayout.setHorizontalGroup(
            LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(113, 113, 113))
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginWindowLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_passw, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LoginWindowLayout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(LoginWindowLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel14)))))
                            .addGroup(LoginWindowLayout.createSequentialGroup()
                                .addComponent(btn_send2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addComponent(Registro)))
                    .addGroup(LoginWindowLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lbl_ip)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        LoginWindowLayout.setVerticalGroup(
            LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_passw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_send2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ip)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel14.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroMouseClicked
        Registro ventana = new Registro();
        ventana.setVisible(true);
    }//GEN-LAST:event_RegistroMouseClicked

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:

        Socket socket;

        try {

            socket = new Socket(ip, 2222);

            String username = txt_usuario.getText();
            String password = txt_passw.getText();

            JSONObject json = new JSONObject();
            json.put("username", username);
            json.put("password", password);

            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
            out.writeObject(json.toString());

            InputStream inn = socket.getInputStream();
            ObjectInputStream in = new ObjectInputStream(inn);
            String jobj = (String) in.readObject();
            json = new JSONObject(jobj);

            String fullname = json.getString("fullname");
            String status = json.getString("status");

            if ("OK".equals(status)) {
                //this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Bienvenido: " + fullname);
                Home inicio = new Home();
                inicio.setVisible(true);
                usernom=username;
            } else {
                
                if("Usuario o Contraseña incorrectos".equals(status)){
                    LoginMessage ventana = new LoginMessage();
                    ventana.setVisible(true);
                } else{
                    JOptionPane.showMessageDialog(null, status);
                }
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            String nl = System.getProperty("line.separator");
            String msg = "Error de conexión en la IP: " + ip + nl + "Intente cambiar la IP del servidor en la" + nl + "opción de debajo de la pantalla de login.";
            JOptionPane.showMessageDialog(null, msg, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn_sendActionPerformed

    private void lbl_ipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ipMouseClicked
        // TODO add your handling code here:
        IP ventana = new IP();
        ventana.setVisible(true);

        IP.txt_ip1.setText(ip1);
        IP.txt_ip2.setText(ip2);
        IP.txt_ip3.setText(ip3);
        IP.txt_ip4.setText(ip4);

    }//GEN-LAST:event_lbl_ipMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(null, "Cerrando sesión");
        Socket socket;
        try {
            socket = new Socket(ip, 2222);
            
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginWindow;
    private javax.swing.JLabel Registro;
    private javax.swing.JButton btn_send2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lbl_ip;
    private javax.swing.JPasswordField txt_passw;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
