/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aurochat;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author elalf
 */
public class Registro extends javax.swing.JFrame {

    public String enc;

    /**
     * Creates new form NewJFrame
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        txt_adduser = new javax.swing.JTextField();
        txt_adduser2 = new javax.swing.JTextField();
        btn_regis = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txt_addpassw2 = new javax.swing.JPasswordField();
        jLabel57 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txt_addpassw = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        lbl_ok = new javax.swing.JLabel();

        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(37, 44, 52));

        jLabel60.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel60.setText("Repite Usuario");

        txt_adduser.setBackground(new java.awt.Color(37, 44, 52));
        txt_adduser.setForeground(new java.awt.Color(255, 255, 255));
        txt_adduser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_adduser.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_adduser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_adduserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_adduserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_adduserKeyTyped(evt);
            }
        });

        txt_adduser2.setBackground(new java.awt.Color(37, 44, 52));
        txt_adduser2.setForeground(new java.awt.Color(255, 255, 255));
        txt_adduser2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_adduser2.setCaretColor(new java.awt.Color(255, 255, 255));

        btn_regis.setBackground(new java.awt.Color(204, 204, 204));
        btn_regis.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_regis.setForeground(new java.awt.Color(51, 51, 51));
        btn_regis.setText("Registrame!");
        btn_regis.setBorder(null);
        btn_regis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regisbtn_send2btn_sendActionPerformed(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel61.setText("Repite Contraseña");

        jLabel56.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel56.setText("Usuario");

        txt_addpassw2.setBackground(new java.awt.Color(37, 44, 52));
        txt_addpassw2.setForeground(new java.awt.Color(255, 255, 255));
        txt_addpassw2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_addpassw2.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_addpassw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addpassw2txt_password3txt_passwordActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel57.setText("Contraseña");

        txt_apellido.setBackground(new java.awt.Color(37, 44, 52));
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_apellido.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel62.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel62.setText("Nombre");

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(204, 204, 204));
        jLabel58.setText("Registrate a");
        jLabel58.setToolTipText("");

        jLabel63.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel63.setText("Apellido");

        jLabel59.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("AuroChat");
        jLabel59.setToolTipText("");

        txt_nombre.setBackground(new java.awt.Color(37, 44, 52));
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_nombre.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aurochat/mess4.png"))); // NOI18N

        txt_addpassw.setBackground(new java.awt.Color(37, 44, 52));
        txt_addpassw.setForeground(new java.awt.Color(255, 255, 255));
        txt_addpassw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_addpassw.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_addpassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addpasswtxt_password2txt_passwordActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aurochat/barra.jpg"))); // NOI18N

        lbl_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aurochat/ok.png"))); // NOI18N
        lbl_ok.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_addpassw2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addpassw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adduser2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(btn_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel58)))
                                .addGap(23, 23, 23)
                                .addComponent(jLabel64))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ok)
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59))
                    .addComponent(jLabel64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ok)
                    .addComponent(txt_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_adduser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_addpassw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_addpassw2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regisbtn_send2btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regisbtn_send2btn_sendActionPerformed
        Socket socket;

        try {

            socket = new Socket(Login.ip, 2223);

            String nombre = txt_nombre.getText();
            String apellido = txt_apellido.getText();
            String username = txt_adduser.getText();
            String username2 = txt_adduser2.getText();
            String password = txt_addpassw.getText();
            String password2 = txt_addpassw2.getText();

            String status = "";

            if (!"".equals(nombre) && !"".equals(apellido) && !"".equals(username) && !"".equals(username2) && !"".equals(password) && !"".equals(password2)) {
                if (username.equals(username2)) {

                    if (password.equals(password2)) {

                        if ("0".equals(enc)) {
                            JSONObject json = new JSONObject();
                            json.put("fullname", nombre + " " + apellido);
                            json.put("username", username);
                            json.put("password", password);

                            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                            out.writeObject(json.toString());

                            InputStream inn = socket.getInputStream();
                            ObjectInputStream in = new ObjectInputStream(inn);
                            
                            String jobj = (String) in.readObject();
                            json = new JSONObject(jobj);
                            
                            status = json.getString("status");

                            System.out.println(status);
                            if ("OK".equals(status)) {
                                JOptionPane.showMessageDialog(null, "Se ha agregado correctamente");
                                enc = "";
                                lbl_ok.setVisible(false);
                            } else {
                                JOptionPane.showMessageDialog(null, status);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Este usuario ya existe");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "La contraseña y la contraseña de confirmacion deben de ser el mismo");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario y el nombre de usuario de confirmacion deben de ser el mismo");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Llena todos los campos");
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_regisbtn_send2btn_sendActionPerformed

    private void txt_addpassw2txt_password3txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addpassw2txt_password3txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addpassw2txt_password3txt_passwordActionPerformed

    private void txt_addpasswtxt_password2txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addpasswtxt_password2txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addpasswtxt_password2txt_passwordActionPerformed

    private void txt_adduserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adduserKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_adduserKeyPressed

    private void txt_adduserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adduserKeyReleased
        // TODO add your handling code here:
        Socket socket;
        String json;

        try {
            socket = new Socket(Login.ip, 2224);
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
            out.writeObject(txt_adduser.getText());

            InputStream inn = socket.getInputStream();
            ObjectInputStream in = new ObjectInputStream(inn);

            try {
                json = (String) in.readObject();
                JSONObject jobj = new JSONObject(json);

                String status = jobj.getString("status");
                if ("OK".equals(status)) {

                    enc = jobj.getString("enc");

                    if ("0".equals(enc)) {
                        lbl_ok.setVisible(true);
                    } else {
                        lbl_ok.setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, status);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (IOException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_adduserKeyReleased

    private void txt_adduserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adduserKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_adduserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regis;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ok;
    private javax.swing.JPasswordField txt_addpassw;
    private javax.swing.JPasswordField txt_addpassw2;
    private javax.swing.JTextField txt_adduser;
    private javax.swing.JTextField txt_adduser2;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
